### ISSUE TITLE
heimserver_blockly.xml lässt sich nicht öffnen

### ISSUE THREAD

**Issue by ghost** [yhallowiegeht/adventsproject_heimserver#1]
In https://blockly.sensebox.de/ardublockly/?lang=de&board=sensebox-mcu# lässt sich die Datei nicht öffnen. Es erfolgt die Fehlermeldung "Ungültige XML"

**Comment by yhallowiegeht** [comment]
Also ich konnte den Fehler leider nicht replizieren. Hast du die Datei aus dem .zip extrahiert, bevor du sie in blockly nutzt? Ich hab die Datei auch nochmal geupdated, aber funktionieren tut es auf jeden Fall mit beiden Dateien unter Chrome (aktuellste) und Windows 10.

**Comment by yhallowiegeht** [comment]
![blockly_adventssketch_xml](https://user-images.githubusercontent.com/38653845/70987752-d524f480-20c0-11ea-9691-aecf0b0b1c7e.gif)

**Comment by ghost** [comment]
Ich habe diese heruntergeladen:
https://github.com/yhallowiegeht/adventsproject_heimserver/blob/master/heimserver_blockly.xml
ist das eine ZIP Datei? Mit der Endung .xml

**Comment by ghost** [comment]
OK, kapiert. Mit der Einzeldatei geht es nicht aber mit allen Dateien im ZIP geht es. Wieder was dazu gelernt :-)
Vielen Dank

**Comment by yhallowiegeht** [comment]
> Ich habe diese heruntergeladen:
> https://github.com/yhallowiegeht/adventsproject_heimserver/blob/master/heimserver_blockly.xml
> ist das eine ZIP Datei? Mit der Endung .xml

Was meinst du denn mit runterladen? Wenn du in github auf die Datei rechtsklickst, gibt es nur die Möglichkeit den Link zu kopieren, dann erhälst du auch eine XML, die enthält aber lediglich den Link zur Datei. Ich hoffe das erklärt, warum blockly damit nichts anfangen kann! 

> OK, kapiert. Mit der Einzeldatei geht es nicht aber mit allen Dateien im ZIP geht es. Wieder was dazu gelernt :-)
> Vielen Dank

Ja, du musst in github schon das ganze Verzeichnis herunterladen :+1:
